language: go
sudo: required

services:
  - docker

go:
  - 1.7.x
  - master


before_install:
  - sudo apt-get install realpath -y
  - docker run -d --name=etcd -p 2379:2379 quay.io/coreos/etcd:v3.0.17

script:
  - make build test test-integrations verify

matrix:
  allow_failures:
  - go: master
  fast_finish: true
