apiVersion: v1
kind: ReplicationController
metadata:
  name: brokersdk
  namespace: brokersdk
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: brokersdk
      volumes:
      - name: etcd-data
        emptyDir: {}
      - name: brokersdk-data
        emptyDir: {}
      containers:
      - name: brokersdk
        image: brokersdk
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: brokersdk-data
           mountPath: /data
        args:
        - "--etcd-servers=http://localhost:2379"
        - "--authentication-skip-lookup"
        - "--cert-dir=/data"
        - "--secure-port=8443"
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.17
        volumeMounts:
         - name: etcd-data
           mountPath: /data
        args:
        - "/usr/local/bin/etcd"
        - "--data-dir=/data"
